[project]
name = "gtrans-static"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "acdh-cfts-pyutils>=0.2",
    "acdh-cidoc-pyutils>=1.11",
    "acdh-tei-pyutils>=1.6",
    "jinja2>=3.1.6",
]
